# https://github.com/marketplace/actions/hugo-deploy-github-pages
name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: alexmerren/website
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
          CNAME: alexmerren.uk
